/**
 * Reads @blocknote/core dist/style.css and writes it as a TypeScript
 * string constant so it can be imported without any webpack CSS pipeline.
 *
 * Run automatically via `postinstall`, or manually with:
 *   node scripts/generate-bn-css.mjs
 */

import { createRequire } from "module";
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";

const require = createRequire(import.meta.url);

const distDir = dirname(require.resolve("@blocknote/core"));
const cssContent = readFileSync(join(distDir, "style.css"), "utf8");

const output = `\
// AUTO-GENERATED by scripts/generate-bn-css.mjs — do not edit by hand.
// Re-run after upgrading @blocknote/core:  node scripts/generate-bn-css.mjs
// This file is gitignored; it is regenerated on every \`pnpm install\`.

const blocknoteCoreCSS = ${JSON.stringify(cssContent)};
export default blocknoteCoreCSS;
`;

const outPath = join(
  dirname(new URL(import.meta.url).pathname),
  "../src/views/blocknote-multi-column/bn-core-css.generated.ts"
);

writeFileSync(outPath, output, "utf8");
console.log("✓ Generated bn-core-css.generated.ts from @blocknote/core dist/style.css");
